var problem=[
    {
        "item":"这是问题的标书11111",
        "short":"zswtdbs1",
        "list":"171",
        "answer":"这是答案的啊啊"
    },
    {
        "item":"这是问题的标书222222",
        "short":"zswtdbs2",
        "list":"172",
        "answer":"这是答案的啊啊"
    },
    {
        "item":"这是问题的标书3333333",
        "short":"zswtdbs3",
        "list":"173",
        "answer":"这是答案的啊啊"
    },
    {
        "item":"这是问题的标书4444444",
        "short":"zswtdbs4",
        "list":"174",
        "answer":"这是答案的啊啊"
    },
    {
        "item":"这是问题的标书555555",
        "short":"zswtdbs5",
        "list":"175",
        "answer":"这是答案的啊啊"
    },
    {
        "item":"这是问题的标书66666",
        "short":"zswtdbs6",
        "list":"176",
        "answer":"这是答案的啊啊"
    }
];