var problem=[
    {
        "item":"炼制药剂一共有四个步骤，分别是？（可阅读《魔域》第一百二十五章查阅答案）",
        "short":"lzyjygysgbzfbs",
        "list":"125",
        "answer":"研磨、提浆、合成、试药"
    },
    {
        "item":"旭日城的五大家族中，哪一个家族最富有？（可阅读《魔域》第一百五十九章查阅答案）",
        "short":"xrcdwdjzznygjzzfy",
        "list":"159",
        "answer":"布莱恩家族"
    },
    {
        "item":"雷诺给费恩叔叔购买‘治疗药水’是几品药剂？（可阅读《魔域》第一百二十四章查阅答案）",
        "short":"lngfessgmzlyssjpyj",
        "list":"124",
        "answer":"一品"
    },
    {
        "item":"雷诺入住在‘热血时代’大酒店哪一间？（可阅读《魔域》第一百七十二章查阅答案）",
        "short":"lnrzzrxsddjdnyj",
        "list":"172",
        "answer":"六楼六号套房"
    },
    {
        "item":"‘水德金身’与‘魔咒意境’相比，谁的意境更高深？（可阅读《魔域》第一百七十七章查阅答案）",
        "short":"sdjsymzyjxbsdyjggs",
        "list":"177",
        "answer":"水德金身"
    },
    {
        "item":"夜晚的旭日城跟白天比起来是如何的？（可阅读《魔域》第一百八十章查阅答案）",
        "short":"ywdxrcgbtbqlsrhd",
        "list":"180",
        "answer":"夜晚有宵禁，万籁俱寂"
    },
    {
        "item":"‘紫翼尸魔’死后留下的九尺巨剑是什么品质？（可阅读《魔域》第一百六十七章查阅答案）",
        "short":"zysmshlxdjcjjssmpz",
        "list":"167",
        "answer":"魂阶"
    },
    {
        "item":"古怪大师一共‘宰了’雷诺多少魔石？（可阅读《魔域》第一百七十章查阅答案）",
        "short":"ggdsygzllndsms",
        "list":"170",
        "answer":"七十万魔石"
    },
    {
        "item":"克劳德把金色‘净化药剂’扔出窗外，被谁捡到了？（可阅读《魔域》第一百七十二至一百七十三章查阅答案）",
        "short":"kldbjsjhyjrccwbsjdl",
        "list":"172173",
        "answer":"亚萨的药童"
    },
    {
        "item":"整个旭日城对于横空出世的金光药剂震撼不已，引发空前的热议。这轰动，堪比？（可阅读《魔域》第一百七十五章查阅答案）",
        "short":"zgxrcdyhkcsdjgyjzhbyyfkqdryzhdkb",
        "list":"175",
        "answer":"城主府当年禅让府主"
    },
    {
        "item":"雷诺识海的墨珠有什么功能？（可阅读《魔域》第一百七十九章查阅答案）",
        "short":"lnshdmzysmgn",
        "list":"179",
        "answer":"布置幻界"
    },
    {
        "item":"雷诺给费恩叔叔购买‘治疗药水’花了多少钱？（可阅读《魔域》第一百二十四章查阅答案）",
        "short":"lngfessgmzlyshldsq",
        "list":"124",
        "answer":"1000金币"
    },
    {
        "item":"雷诺初入斗将境，体内的脉轮分别是？（可阅读《魔域》第一百七十三章查阅答案）",
        "short":"lncrdjjtndmlfbs",
        "list":"173",
        "answer":"海底轮，灵泉轮"
    },
    {
        "item":"在没有得到任何金光药剂师的消息时，亚萨大师很颓然，很落寞，真正原因是？（可阅读《魔域》第一百七十七章查阅答案）",
        "short":"zmyddrhjgyjsdxxsysdshtrhlmzzyys",
        "list":"177",
        "answer":"损失与能者论道的机会"
    },
    {
        "item":"雷诺自打入住‘热血时代’大酒店，已经多久没有出门了？克劳德表示很心焦？（可阅读《魔域》第一百七十七至一百七十八章查阅答案）",
        "short":"lnzdrzrxsddjdyjdjmycmlkldbshxj",
        "list":"177178",
        "answer":"整整7天"
    },
    {
        "item":"‘魔法百科’上说，‘神书’是被一个叫做‘___’的人首次发现的？（可阅读《魔域》第一百八十章查阅答案）",
        "short":"mfbksssssbygjzdrscfxd",
        "list":"165",
        "answer":"昂"
    },
    {
        "item":"克劳德对雷诺下手的目的是要将雷诺的身体炼制成？（可阅读《魔域》第九十二至九十三章查阅答案）",
        "short":"klddlnxsdmdsyjlndstlzc",
        "list":"9293",
        "answer":"百毒之体"
    },
    {
        "item":"‘水德幻境’与‘水德金身’是什么关系？（可阅读《魔域》第一百七十八章查阅答案）",
        "short":"sdhjysdjssssgx",
        "list":"178",
        "answer":"‘水德幻境’乃是‘水德金身’的至高形态"
    },
    {
        "item":"旭日城城主举办‘万药大会’，派出李副官前去邀请谁来主持大会？（可阅读《魔域》第一百七十七章查阅答案）",
        "short":"xrcczjbwydhpclfgqqyyslzcdh",
        "list":"177",
        "answer":"亚萨"
    },
    {
        "item":"雷诺入住‘热血时代’大酒店，为什么让克劳德很是伤脑筋？（可阅读《魔域》第一百七十二章查阅答案）",
        "short":"lnrzrxssdjdwsmrkldhssnj",
        "list":"172",
        "answer":"以上皆是"
    },
    {
        "item":"金色'净化药剂'对‘望齿魔人’的毒素的净化效果是？（可阅读《魔域》第一百七十四章查阅答案）",
        "short":"jsjhyjdwcmrddddjhxgs",
        "list":"174",
        "answer":"百分之百"
    },
    {
        "item":"‘紫影魔蝎’和‘紫翼尸魔’谁的毒更厉害？（可阅读《魔域》第一百七十九章查阅答案）",
        "short":"zymxhzysmsddglh",
        "list":"179",
        "answer":"紫影魔蝎"
    },
    {
        "item":"雷诺找了谁来解读刻在‘紫翼尸魔’死后留下的九尺巨剑上的魔咒？（可阅读《魔域》第一百六十八章查阅答案）",
        "short":"lnzlsljdkzzysmshlxdjcjjsdmz",
        "list":"168",
        "answer":"古怪大师"
    },
    {
        "item":"战狼佣兵团的团长和副团长之间是什么关系？（可阅读《魔域》第一百二十八章查阅答案）",
        "short":"zlybtdtzhftzzjsssgx",
        "list":"128",
        "answer":"兄妹"
    },
    {
        "item":"前来击杀雷诺的杀手--来自魔族后裔中的云豹，是什么修为？（可阅读《魔域》第一百八十章查阅答案）",
        "short":"qljslndsslzmzhyzdybssmxw",
        "list":"180",
        "answer":"斗将巅峰"
    },
    {
        "item":"‘永旭拍卖行’与‘蓝天交易所’是隶属于哪一个家族的产业？（可阅读《魔域》第一百五十九章查阅答案）",
        "short":"yxpmhyltjysslsynygjzdcy",
        "list":"159",
        "answer":"布莱恩家族"
    },
    {
        "item":"雷诺炼制的‘金色净化药剂’在‘仁德药剂堂’寄售了多少钱？（可阅读《魔域》第一百二十七章查阅答案）",
        "short":"lnlzdjsjhyjzrdyjtjsldsq",
        "list":"127",
        "answer":"50000金币"
    },
    {
        "item":"雷诺闭关参悟‘魔咒意境’与‘水德金身’，结果如何？（可阅读《魔域》第一百七十八章查阅答案）",
        "short":"lnbgcwmzyjysdjsjgrh",
        "list":"178",
        "answer":"‘魔咒意境’与‘水德金身’双双领悟"
    },
    {
        "item":"克劳德看到魔法屏幕上，各种吹捧无名金光药剂师的时候，是什么感受？（可阅读《魔域》第一百七十六章查阅答案）",
        "short":"kldkdmfpmsgzcpwmjgyjsdshssmgs",
        "list":"176",
        "answer":"以上皆是"
    },
    {
        "item":"雷诺体中灵泉轮的女神容貌是？（可阅读《魔域》第一百七十三章查阅答案）",
        "short":"lntzlqldnsrms",
        "list":"173",
        "answer":"冷傲"
    },
    {
        "item":"‘蓝天交易所’与‘永旭拍卖行’哪个比较豪华？（可阅读《魔域》第一百六十六章查阅答案）",
        "short":"ltjysyyxpmhngbjhh",
        "list":"166",
        "answer":"蓝天交易所"
    },
    {
        "item":"古怪大师的背后有三个坛子，分别是绿色，黄色，红色，每个坛子上分别贴着一个字条，分别对应着？（可阅读《魔域》第一百六十九章查阅答案）",
        "short":"ggdsdbhysgtzfbslshshsmgtzsfbtzygztfbdyz",
        "list":"169",
        "answer":"小事五千、大事五万，秘辛五十万"
    },
    {
        "item":"雷诺打算找谁重铸魔剑？（可阅读《魔域》第一百八十一章查阅答案）",
        "short":"lndszsczmj",
        "list":"181",
        "answer":"史密斯家族"
    },
    {
        "item":"‘魔咒意境’真言曰：瀚海狂澜万里凝，大浪磅礴渺苍穹。浮天叠浪傲云志，只缘潮汐无始终。这四句真言的精华是“__”？（可阅读《魔域》第一百七十六章查阅答案）",
        "short":"mzyjzyyhhklwlndlpbmcqftdlayzzycxwszzsjzydjhs",
        "list":"176",
        "answer":"潮汐"
    },
    {
        "item":"在混乱大陆，兵器按照威能强弱的品阶基本划分为？（可阅读《魔域》第一百六十七章查阅答案）",
        "short":"zhldlbqazwnqrdpjjbhfw",
        "list":"167",
        "answer":"凡阶、宝阶、玄阶、魂阶、荒阶、神阶、圣阶"
    },
    {
        "item":"‘药剂师联盟’的司长是谁？（可阅读《魔域》第一百七十一至一百七十二章查阅答案）",
        "short":"yjslmdszss",
        "list":"171172",
        "answer":"克劳德"
    },
    {
        "item":"为了不把‘药剂师联盟’变成菜市场，药剂师的报名地点设在哪里？（可阅读《魔域》第一百七十一章查阅答案）",
        "short":"wlbbyjslmbccscyjsdbmddsznl",
        "list":"171",
        "answer":"‘药剂师联盟’小门"
    },
    {
        "item":"克劳德在酒店外埋伏了杀手，但是却毫无收获，原因是？（可阅读《魔域》第一百七十六章查阅答案）",
        "short":"kldzjdwmflssdsqhwshyys",
        "list":"176",
        "answer":"以上都是"
    },
    {
        "item":"古怪大师与雷诺的父亲苏天华是什么关系？（可阅读《魔域》第一百七十章查阅答案）",
        "short":"ggdsylndfqsthsssgx",
        "list":"170",
        "answer":"好友"
    },
    {
        "item":"‘魔法测力碑’最高可测多少斤力？（可阅读《魔域》第一百七十三章查阅答案）",
        "short":"mfclbzgkcdsjl",
        "list":"173",
        "answer":"十万斤"
    },
    {
        "item":"‘蓝天交易所’与‘永旭拍卖行’谁的楼比较高？（可阅读《魔域》第一百六十六章查阅答案）",
        "short":"ltjysyyxpmhsdlbjg",
        "list":"166",
        "answer":"永旭拍卖行"
    },
    {
        "item":"旭日城城主之子御东皇所中的是什么毒？（可阅读《魔域》第一百七十七章查阅答案）",
        "short":"xrcczzzydhszdssmd",
        "list":"177",
        "answer":"‘紫影魔蝎’之毒"
    },
    {
        "item":"雷诺体中海底轮的女神容貌是？（可阅读《魔域》第一百七十三章查阅答案）",
        "short":"lntzhdldnsrms",
        "list":"173",
        "answer":"温柔"
    },
    {
        "item":"‘旭日拍卖行’分区执行官艾伦对XXXXXX无名药剂师的态度是？（可阅读《魔域》第一百七十五章查阅答案）",
        "short":"xrpmhfqzxgald wmyjsdtds",
        "list":"175",
        "answer":"想拉拢他"
    },
    {
        "item":"雷诺初入斗将境，用‘魔法测力碑’测出的拳力是多少？（可阅读《魔域》第一百七十四章查阅答案）",
        "short":"lncrdjjymfclbccdqlsds",
        "list":"174",
        "answer":"三万五千斤"
    }
];